@echo off
setlocal enabledelayedexpansion
setlocal enableextensions

:: Execute the verify SQL*PLUS script to determine which scripts are late in their execution.
sqlplus -s %SQL_PLUS_USERNAME%@%SQL_PLUS_DATABASE% <"%SQL_PLUS_PASSWORD_FILE_PATH%" @verify.pdc "%APP_TEMP_DIRECTORY_PATH%"

:: Execute the verify VBScript script to display the messages generated by the previous command.
cscript /NoLogo "verify.vbs" <"%APP_TEMP_DIRECTORY_PATH%\messages.txt"

:: Delete the temporary messages file.
del "%APP_TEMP_DIRECTORY_PATH%\messages.txt"
